name: me0ws-light
# The native container image to build on top of.
# Warning: Non-uBlue images might not work properly, due to missing components.
base-image: ghcr.io/ublue-os/silverblue-main
fedora-version: 38
description: me0ws is built on top of silverblue[ublue] with light weight window managers in mind
scripts:
  pre:
    - autorun.sh
  post:
    - autorun.sh
rpm:
  repos:
  install:
    - python3-pip
    - libadwaita
  remove:
    - firefox
    - firefox-langpacks
firstboot:
  yafti: true
  flatpaks:
